export const navigation = [
  { href: "/", label: "Start" },
  { href: "/aktualnosci", label: "Aktualności" },
  { href: "/jak-kupic", label: "Jak kupić?" },
  { href: "/wsparcie", label: "Wsparcie" },
  { href: "/zasieg", label: "Zasięg" },
  { href: "/cennik", label: "Cennik" },
  { href: "/kontakt", label: "Kontakt" },
  { href: "/regulamin", label: "Regulamin" },
  { href: "/o-nas", label: "Kim jesteśmy" },
] as const;

export const packages = [
  {
    name: "AirFiber 5 ECONO",
    speed: "5 / 5 Mbps",
    price: "50 zł",
    installation: "1 zł",
  },
  {
    name: "AirFiber 8",
    speed: "8 / 8 Mbps",
    price: "65 zł",
    installation: "1 zł",
  },
  {
    name: "AirFiber 12",
    speed: "12 / 12 Mbps",
    price: "80 zł",
    installation: "1 zł",
  },
  {
    name: "AirFiber 16",
    speed: "16 / 16 Mbps",
    price: "90 zł",
    installation: "1 zł",
  },
  {
    name: "AirFiber 20",
    speed: "20 / 20 Mbps",
    price: "100 zł",
    installation: "1 zł",
  },
  {
    name: "AirFiber 30",
    speed: "30 / 30 Mbps",
    price: "110 zł",
    installation: "1 zł",
  },
] as const;

export const coveragePlaces = [
  "Iłża",
  "Alojzów",
  "Białka",
  "Błaziny",
  "Bujak",
  "Chwałowice",
  "Ciecierówka",
  "Florencja",
  "Jasieniec Iłżecki",
  "Kotlarka",
  "Krupów",
  "Krzyżanowice",
  "Łączany",
  "Małomierzyce",
  "Małyszyn",
  "Mirów",
  "Mirów Nowy",
  "Mirów Stary",
  "Mirówek",
  "Mirzec",
  "Modrzejowice",
  "Osiny",
  "Osiny Majorat",
  "Pakosław",
  "Pasztowa Wola",
  "Pasztowa Wola-Kolonia",
  "Pastwiska",
  "Pieńki",
  "Płósy",
  "Podkońce",
  "Polany",
  "Polany-Kolonia",
  "Pomorzany",
  "Prędocin",
  "Prędocin-Kolonia",
  "Rzechów",
  "Rzechów-Kolonia",
  "Rzeczniów",
  "Rzeczniówek",
  "Seredzice",
  "Starosiedlice",
  "Stary Rzechów",
  "Suliszka",
  "Trębowiec",
  "Walentynów",
  "Wierzbica",
  "Zalesice",
  "Zalesice-Opoka",
] as const;

export const news = [
  {
    date: "2014-09-06",
    title: "Kolejny obszar pokryty zasięgiem sieci Iłża.Net",
    text: "Od 6 września 2014 roku Prędocin, Prędocin-Kolonia, Pasztowa Wola, Pasztowa Wola-Kolonia, Ciecierówka, Podkońce, Rzechów, Rzechów-Kolonia, Stary Rzechów, Rzeczniówek, Rzeczniów i Płósy zostały objęte zasięgiem sieci Iłża.Net w technologii FLASH.",
  },
  {
    date: "2014-08-27",
    title: "Ilza.Net AirFiber — nowa technologia, nowa oferta",
    text: "Rozpoczęliśmy wdrażanie technologii firmy Ubiquiti, pozwalającej przesyłać dane z prędkością do 1 gigabita na sekundę. W wybranych miejscowościach pojawiła się oferta Ilza.Net AirFiber.",
  },
  {
    date: "2013-02-09",
    title: "Gmina Mirów w zasięgu",
    text: "Usługi Ilza.Net stały się dostępne dla mieszkańców miejscowości Mirów Stary, Mirów, Mirów Nowy, Osiny, Osiny Majorat, Krupów oraz Trębowiec.",
  },
  {
    date: "2012-12-03",
    title: "Ilza.Net na nowych terenach",
    text: "Sieć objęła kolejne obszary: Walentynów, Florencję, Pieńki, Alojzów, Bujak i Modrzejowice.",
  },
  {
    date: "2012-07-13",
    title: "Burze niszczą sprzęt?",
    text: "Rozpoczął się sezon burzowy. Przypominaliśmy, jak ograniczyć ryzyko uszkodzeń sprzętu wywołanych wyładowaniami atmosferycznymi.",
  },
  {
    date: "2012-04-30",
    title: "Iłża.Net na nowym terenie",
    text: "Usługi sieci Iłża.Net stały się dostępne w Małomierzycach.",
  },
  {
    date: "2011-03-31",
    title: "Iłża.Net FLASH — do 150 Mbit/s drogą radiową",
    text: "Nowa technologia dostępowa FLASH pozwalała zestawiać połączenia radiowe do 150 Mbit/s. Oferta obejmowała Iłżę, Krzyżanowice, Seredzice i Pakosław.",
  },
  {
    date: "2011-01-07",
    title: "Nowe ceny instalacji Internetu w sieci Iłża.Net",
    text: "Mimo zmiany stawek VAT ceny abonamentów pozostały na dotychczasowym poziomie, a od 1 stycznia zaczęły obowiązywać niższe stawki instalacyjne.",
  },
  {
    date: "2010-12-03",
    title: "Routery Wi-Fi dostępne w naszym sklepie",
    text: "W sklepie pojawiły się routery TP-LINK. Abonenci Iłża.Net otrzymywali 3% rabatu na zakupy.",
  },
  {
    date: "2010-09-15",
    title: "Nowa oferta na jesień",
    text: "Dopłata 10 zł do abonamentu pozwalała podwoić prędkość łącza.",
  },
  {
    date: "2010-09-14",
    title: "Nowe miejscowości w zasięgu sieci Iłża.Net",
    text: "Zasięg sieci powiększył się o Wierzbicę, Zalesice, Polany-Kolonię, Łączany, Suliszkę, Podsuliszkę, Zalesice-Opokę, Mirówek i Mirów Nowy.",
  },
  {
    date: "2010-07-23",
    title: "Darmowy Internet na Święcie Iłży 2010",
    text: "Iłża.Net zapewniła bezpłatny bezprzewodowy dostęp do Internetu na terenie imprezy Święto Iłży 2010.",
  },
  {
    date: "2010-05-06",
    title: "Nowe zasady podłączenia do sieci Iłża.Net",
    text: "Dla umowy dwuletniej koszt instalacji wynosił 1,22 zł, dla rocznej 150 zł, a dla umowy na czas nieokreślony 300 zł. Podane ceny były cenami brutto.",
  },
  {
    date: "2010-02-10",
    title: "Piętnastominutowa przerwa w dostępie do Internetu",
    text: "Między godziną 11:00 a 12:00 wystąpiła piętnastominutowa przerwa u jednego z dostawców, która spowodowała degradację usług w całej sieci. Awaria została szybko usunięta.",
  },
  {
    date: "2010-02-06",
    title: "Wymiana urządzeń na stacji w Pastwiskach",
    text: "Zapowiedziano prace rozbudowujące stację obsługującą Pastwiska, Błaziny, Koszary, Białkę i Kotlarkę oraz możliwe krótkie przerwy w dostępie.",
  },
  {
    date: "2010-02-04",
    title: "Modernizacja stacji na ul. Wójtowskiej",
    text: "Na 6 lutego 2010 r. zapowiedziano modernizację stacji i przerwę dla Chwałowic, Krzyżanowic, Starosiedlic, Florencji, Pomorzan, Polan oraz części Iłży.",
  },
  {
    date: "2010-01-28",
    title: "Konkurs Iłża.Net rozstrzygnięty",
    text: "Wśród osób, które skorzystały z aktualnej wówczas oferty, rozlosowano dwa podwójne zaproszenia do pizzerii Isola Bella.",
  },
  {
    date: "2010-01-20",
    title: "Niespodzianka od Iłża.Net i restauracji Isola Bella",
    text: "Nowi i obecni klienci mogli otrzymać podwójne zaproszenie do włoskiej restauracji. Losowania prowadzono co miesiąc.",
  },
  {
    date: "2010-01-15",
    title: "Awaria usunięta",
    text: "Po ponad dwóch dniach problemów po stronie dostawcy transmisja została przywrócona, a usługi wróciły do właściwego stanu.",
  },
  {
    date: "2010-01-14",
    title: "Prace u dostawcy miały potrwać do 15 stycznia",
    text: "Operator informował, że usuwanie awarii u dostawcy łączy może potrwać do godzin popołudniowych następnego dnia.",
  },
  {
    date: "2010-01-13",
    title: "Awaria u jednego z dostawców",
    text: "Powalone drzewo w okolicy Skarżyska zerwało linię energetyczną, do której podwieszony był światłowód. Skutkiem była wolniejsza transmisja w całej sieci.",
  },
  {
    date: "2010-01-05",
    title: "Dedykowany serwer Counter-Strike w sieci Iłża.Net",
    text: "W sieci został uruchomiony dedykowany serwer gry Counter-Strike 1.6.",
  },
  {
    date: "2010-01-04",
    title: "Wyjątkowe tapety do pobrania",
    text: "Udostępniliśmy widoki Iłży i jej okolic przygotowane jako tapety komputerowe.",
  },
  {
    date: "2009-12-30",
    title: "Życzenia noworoczne od Iłża.Net",
    text: "Ekipa Iłża.Net przekazała klientom życzenia noworoczne.",
  },
  {
    date: "2009-12-10",
    title: "Iłża.Net V-ULTRA — pakiet dla wymagających",
    text: "Rosnące możliwości techniczne i zapotrzebowanie na pasmo zaowocowały przygotowaniem najszybszego wówczas pakietu internetowego na lokalnym rynku.",
  },
  {
    date: "2009-11-02",
    title: "Modernizacja stacji Krzyżanowice Kościół",
    text: "Zapowiedziano modernizację stacji zainstalowanej na kościele w Krzyżanowicach i możliwe chwilowe przerwy w jej działaniu.",
  },
  {
    date: "2009-10-17",
    title: "Sezon modernizacji sieci zakończony",
    text: "Po kilku tygodniach prac zakończono zaplanowaną modernizację sieci, finalizując prace na stacji Pastwiska.",
  },
  {
    date: "2009-10-03",
    title: "Internet Hotspot Iłża.Net",
    text: "Uruchomiliśmy pierwszy ogólnodostępny, bezpłatny punkt dostępu do Internetu na rynku w Iłży.",
  },
  {
    date: "2009-10-01",
    title: "Nowe pakiety w Iłża.Net",
    text: "Od 1 października wprowadzono nowe, szybsze pakiety internetowe.",
  },
  {
    date: "2009-09-23",
    title: "Modernizacja stacji Jasieniec Kościół",
    text: "Modernizacja stacji w Jasieńcu Iłżeckim miała poprawić jakość usług w Jasieńcu oraz Małyszynie.",
  },
] as const;

export const regulationSections = [
  {
    title: "Postanowienia ogólne",
    paragraphs: [
      "Sieć operatora (Ilza.Net) działa na terenie gminy Iłża. Została zbudowane na życzenie mieszkańców celem udostępnienia łączy internetowych poszczególnym klientom. Budowa sieci została sfinansowana ze środków własnych firmy.",
      "Właścicielem sieci szkieletowej pozostaje firma GTR Systemy.",
      "Firma GTR Systemy dzierżawi od swojego operatora łącze internetowe w oparciu, o które realizowany jest dostęp do sieci internetowej.",
      "W ramach oferowanej usługi Ilza.Net firma zapewnia:",
      "stały dostęp do sieci Internet za pośrednictwem bezprzewodowej sieci strukturalnej;",
      "zachowanie tajemnicy telekomunikacyjno - informatycznej, nie przekazywanie informacji o rodzaju i charakterze połączeń Abonenta osobom trzecim, poza przypadkami przewidzianymi przepisami prawa;",
      "Firma GTR Systemy nie gwarantuje przepustowości transmisji do poszczególnych zasobów internetowych.",
    ],
  },
  {
    title: "Przyłączenie do sieci, opłaty, rezygnacja z usługi",
    paragraphs: [
      "Uruchomienie łącza dostępowego do sieci Ilza.Net następuje w dniu podpisania umowy i wniesieniu opłaty instalacyjnej. Opłata instalacyjna jest opłatą za zestawienie połączenia do sieci Ilza.Net. Zainstalowany sprzęt pozostaje własnością firmy GTR Systemy.",
      "Opłata abonamentowa za korzystanie z sieci Ilza.Net wnoszona jest do 20-go danego miesiąca.",
      "Abonent we własnym zakresie pilnuje terminów płatności, firma GTR Systemy nie wysyła pisemnych zawiadomień o zaległościach.",
      "Nieopłacenie miesięcznej opłaty w terminie powoduje zablokowanie dostępu do sieci Ilza.Net. Ponowne podłączenie do sieci następuje po uregulowaniu zaległych opłat.",
      "Za czas kiedy użytkownik pozbawiony jest dostępu do sieci z powodu nie opłacenia w terminie abonamentu, nie przysługuje zwrot bądź zmniejszenie opłaty miesięcznej.",
      "Nie opłacenie miesięcznej opłaty abonamentowej, równoważne jest odłączeniu od sieci, zawieszeniu usługi, lecz nie jest równoważne z wypowiedzeniem umowy.",
      "Zawieszenie możliwości korzystania z sieci Ilza.Net jest bezpłatne. Operator powinien zostać poinformowany o zawieszeniu usług przed rozpoczęciem okresu rozliczeniowego w którym zawieszenie ma nastąpić.",
      "Ponowne podłączenie do sieci następuje po uregulowaniu opłaty za bieżący okres użytkowania (do końca okresu rozliczeniowego).",
      "Umowa zawarta na czas nieokreślony może zostać rozwiązana przez abonenta w każdym momencie z zachowaniem jednego pełnego, miesięcznego okresu rozliczeniowego poprzez złożenie pisemnego wypowiedzenia.",
      "GTR Systemy może rozwiązać umowę z abonentem w trybie natychmiastowym, szczególnie w przypadku złamania przez abonenta warunków umowy, netykiety, lub działania niezgodnego z obowiązującym prawem.",
    ],
  },
  {
    title: "Obowiązki użytkownika Sieci",
    paragraphs: [
      "Uzytkwonik jest zobowiązany do podłączenia urządzeń znajdujacych sie na dachu budynku do instalacji odgromowej. Operator uslugi Ilza.Net nie ponosi odpowiedzialnosci za szkody powstale w skutek wyladowan atmosferycznych.",
      "Użytkownik zobowiązany jest do skonfigurowania swojego sprzętu i instalacji oprogramowania do korzystania z sieci we własnym zakresie. Utrzymywanie porządku i pielęgnacja komputera nie jest częścią usługi dostępu do sieci, aczkolwiek w okresie rozruchowym użytkownicy mogą liczyć na jednorazową pomoc w konfiguracji sprzętu i oprogramowania do pracy z siecią. GTR Systemy w ramach usługi Ilza.Net nie prowadzi serwisu komputerów klienta tzn. ewentualne konflikty sprzętowe uniemożliwiające poprawną pracę komputera w sieci, klient zobowiązany jest wykonać we własnym zakresie lub zlecić jako dodatkową usługę.",
      "Użytkownik we własnym zakresie dba o bezpieczeństwo swoich danych. GTR Systemy nie ponosi odpowiedzialności za przeprowadzone przez użytkownika transakcje handlowe dokonane za pośrednictwem Internetu. Nie odpowiada również, za działanie pobranego z sieci oprogramowania, ani za ewentualne szkody spowodowane bezpośrednio bądź pośrednio przez to, że użytkownik za pośrednictwem sieci Ilza.Net korzystał z Internetu.",
      "Użytkownik odpowiada za podejmowane przez siebie działania, ze szczególnym uwzględnieniem działań mogących stanowić naruszenie przepisów prawa, w tym prawa autorskiego. W szczególności z konsekwencjami muszą liczyć się osoby pobierające i udostępniające w sieci nielegalne pliki muzyczne, video i oprogramowanie.",
      "Użytkownik zobowiązuje się do przestrzegania zasad korzystania z sieci komputerowej. W szczególności nie podłączania do sieci urządzeń niesprawnych, źle skonfigurowanych, bądź nie przeznaczonych do pracy w sieci.",
      "Wszelkie sytuacje awaryjne należy zgłaszać niezwłocznie po ich zauważeniu. Zgłoszenia awarii należy dokonać telefonicznie lub za pomocą poczty elektronicznej (biuro@ilza.net).",
      "Użytkownik dba o swój sprzęt komputerowy we własnym zakresie. Na czas gwałtownej burzy ze względów bezpieczeństwa należy odłączyć komputer od sieci dla uniknięcia możliwości uszkodzenia go przez wyładowania atmosferyczne.",
      "Użytkownikowi nie wolno zmienić własnej konfiguracji sieciowej pod groźbą zawieszenia dostępu do sieci. W szczególności natychmiastowe karne odłączenie od sieci następuje w przypadku zmiany przydzielonych numerów IP.",
      "Użytkownik zobowiązuje się do terminowego wnoszenia wymienionych w cenniku opłat miesięcznych za korzystanie z sieci.",
    ],
  },
  {
    title: "Prawa użytkownika Sieci",
    paragraphs: [
      "Użytkownicy mają prawo domagać się sprawnego działania sieci i szybkiej reakcji firmy na zgłaszane usterki.",
      "W przypadku przerwy pracy sieci nie wynikającej z winy użytkownika, a dłuższej niż 24h przysługuje możliwość zwolnienia z opłat abonamentowych za bieżący miesiąc, tylko w przypadku upłynięcia wspomnianych 24h od momentu zgłoszenia awarii.",
      "Użytkownicy będą powiadamiani o wszelkich planowanych dłuższych niż 1 godzina przerwach w dostępie do Internetu na stronach Ilza.Net (np. związanych z pracami konserwacyjnymi) z odpowiednim czasowym wyprzedzeniem.",
    ],
  },
  {
    title: "Karne odłączenie od sieci",
    paragraphs: [
      "Karne odłączenie od sieci następuje za rażące naruszenie zasad użytkowania sieci.",
      "Karne odłączenie od sieci może nastąpić w wypadku:",
      "Zmiany przez użytkownika przydzielonego mu adresu IP;",
      "Próby naruszenia prywatności innych użytkowników sieci poprzez wykorzystanie nielegalnie zdobytych kodów bezpieczeństwa, haseł i tym podobnych metod;",
      "Działania na szkodę innych użytkowników sieci, takich jak podszywanie się pod inne osoby, wysyłanie poczty w imieniu innych użytkowników, próby włamania na komputery, rozsyłanie wirusów itp.;",
    ],
  },
  {
    title: "Postanowienia końcowe",
    paragraphs: [
      "GTR Systemy zastrzega sobie prawo dochodzenia niezapłaconych należności nawet mimo rozwiązania lub wygaśnięcia Umowy o przyłączeniu i korzystaniu z sieci komputerowej. Zakres usługi, maksymalną prędkość transmisji określa cennik. Do wyboru użytkownika są różne plany abonamentowe. Jeżeli użytkownik nie wybrał żadnego z planów abonamentowych zakłada się iż będzie korzystał z usług sieci na zasadach określonych przez abonament \"Nowa Taryfa Ilza.Net V-Średni\"",
      "W sprawach nieuregulowanych umową stosuje się odpowiednie przepisy kodeksu cywilnego.",
      "Właściwym do rozstrzygania sporów wynikających z umowy o przyłączeniu i korzystaniu z sieci internetowej jest sąd powszechny właściwy miejscowo dla miejsca zawarcia umowy.",
      "Abonent wyraża zgodę na przetwarzanie i udostępnianie swych danych osobowych operatorowi (zgodnie z art. 24 ustawy z dnia 29 sierpnia 1997 r. o ochronie danych osobowych t.j. Dz.U. z 2002 r. Nr 101, poz 926 ze zm.), w celach marketingowych, świadczenia usług.",
    ],
  },
] as const;
